### PR TITLE
issue#29_nautilus_feedback_to_ui

### PR DESCRIPTION
**Pull request by seg1129**
This is adding LIMS error messages to the biorepo-portal UI when there is an issue rendering aliquots.

### CODE REVIEW

**Comment by tjrivera** [comment]
It looks like you're merging master into dev at 1ff18ab. Why is that? 

Generally, I would rebase this into a few commits. Right now there are some dupes, and you'd want to structure your commits into logical parts to create a nice linear history so that when reading back its clear what change happened where. 

There's a nice tutorial on how to do an interactive rebase (and why) [here](https://www.atlassian.com/git/tutorials/rewriting-history#git-rebase-i)

Try to find a good balance between cramming a bunch of changes into one commit vs. many many small commits for small one off things. Ideally, they should be logical units of change or components that support the overall feature your branch represents.

**Comment by seg1129** [comment]
interesting! I'm not sure why commit says, "merge branch 'master' into dev" at the top of the pull request it says, "seg1129  wants to merge 13 commits into master from dev" and when I review the changed code it is from dev not master. I'll do a rebase instead of merge. Thanks for the tutorial!

**Comment by tjrivera** [comment]
I would check out the pull request history on https://github.com/chop-dbhi/avocado/ since its extensive and provides good examples

**Comment by seg1129** [comment]
so when I move code to dev - I should also rebase there so the commits are cleaned up?

**Comment by tjrivera** [comment]
It's probably easier to do your rebase locally. I've seen people rebase to
better explain a PR and then pending review squash everything down to one
commit. I don't know if that's necessary but it would probably be best to
pare things down a bit before things go to a review

**Comment by seg1129** [comment]
ok, that makes sense. Thanks for the feedback!

**Pull request merged**
